### ISSUE TITLE
    import self_cuda_backend as _ext ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Hummels0214** [GewelsJI/VPS#11]
hi I have followed [Upgrade environment for NS block.pdf] from step1 to step5 but it still doesn't work. How can I solves this problem?
thanks

**Comment by Hummels0214** [comment]
Hi,
I have built setup.py but when I tried to run my_train.py it told me ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory,  when I step into this error I found there is no self_cuda_backend in PNSPlusModule.py. I have tried Upgrade environment for NS block.pdf but it doesn't work.
My cuda version is 11.4 which same with pdf's.How can I solves this problem.
Thanks,
Hummels

**Comment by johnson111788** [comment]
Hi,

Thank you for the information.

Are there any error messages during installation?

Best,
Johnson

**Comment by Hummels0214** [comment]
By the way,  my cuda version is 11.4 and my torch version is 1.7.1. I found your pdf suggest torch version is 1.7.0 but it didn't match my cuda version.
Thanks,
Hummels
@

**Comment by Hummels0214** [comment]
When I follow the pdf, I didn't meet any error. I have changed my python version to 3.6.13, modified nvcc_args, modified cxx_args, and when I built setup.py, it told me ''Creating /home/ti-2/.conda/envs/PNS+/lib/python3.6/site-packages/self-cuda.egg-link (link to .)
self-cuda 0.0.0 is already the active version in easy-install.pth
Installed /home/ti-2/Desktop/VPS-main/lib/module/PNS
Processing dependencies for self-cuda==0.0.0
Finished processing dependencies for self-cuda==0.0.0
''
I doubt setup.py doesn't work.
Thanks 
Hummels

**Comment by johnson111788** [comment]
I tried installing it on cuda 11.7 and succeeded.

During installation, I modified CMakeLists.txt and met no error:
```
diff --git a/lib/module/PNS/PNS_Module/CMakeLists.txt b/lib/module/PNS/PNS_Module/CMakeLists.txt
--- a/lib/module/PNS/PNS_Module/CMakeLists.txt
+++ b/lib/module/PNS/PNS_Module/CMakeLists.txt
@@ -1,3 +1,12 @@
+get_directory_property(dir_defs DIRECTORY ${CMAKE_SOURCE_DIR} 
+COMPILE_DEFINITIONS) 
+set(vtk_flags) 
+foreach(it ${dir_defs}) 
+    if(it MATCHES "vtk*") 
+    list(APPEND vtk_flags ${it}) 
+    endif() 
+endforeach()
+
 cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
 project(SA)

```

If possible, could you provide your whole installation log? Or even better, you could downgrade the cuda version to meet the original requirement.

**Comment by Hummels0214** [comment]
Hi,
I have solved this problem, I changed cuda version to 11.0 but didn't change setup.py, fortunately it works
thanks for your answers!
